{% set python_min = "3.10" %}
{% set name = "pymc-marketing" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 698f507449aa3a98110f78c9c3e619d9cd24a5992c5a0ec127963e1595f840d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling <2
    - hatch-fancy-pypi-readme
    - pip
  run:
    - pytensor >=2.30.3
    - python >={{ python_min }}
    - arviz >=0.13.0
    - matplotlib-base >=3.5.1
    - numpy >=1.17
    - pandas
    - pydantic >=2.1.0
    - pymc >=5.22.0
    - pytensor-base >=2.30.3
    - scikit-learn >=1.1.1
    - seaborn >=0.12.2
    - xarray >=2024.1.0
    - xarray-einstats >=0.5.1
    - pyprojroot
    - preliz >=0.8.0

test:
  imports:
    - pymc_marketing
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Marketing Statistical Models in PyMC
  home: https://github.com/pymc-labs/pymc-marketing
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - twiecki
    - ricardoV94
    - drbenvincent
